### ISSUE TITLE
whether the atomic_server ( with browser UI)   can deploy independent ? I meaning offline or isolate

### ISSUE THREAD

**Issue by iRobinZhang** [atomicdata-dev/atomic-data-rust#604]
looks the Rect js code contains many hard code that point to  "http://atomicdata.dev" , especial in Datatype,  

so  it is necessary for running the atomic_server ?

**Comment by joepio** [comment]
Yes, it should be able to run without an internet connection. The server's binary file actually contains the atomicdata.dev ontology, which includes all properties / classes used by default.

**Comment by iRobinZhang** [comment]
the file 'datatypes.ts' in the  data-browser project ,  it was defined like :

`export enum Datatype {
  /** A Resource - either a URL string or a Nested Resource */
  ATOMIC_URL = 'https://atomicdata.dev/datatypes/atomicURL',
  /** True / false */
  BOOLEAN = 'https://atomicdata.dev/datatypes/boolean',
  /** ISO date YYYY-MM-DD */
  DATE = 'https://atomicdata.dev/datatypes/date',
  /** Floating point number (number with comma) */
  FLOAT = 'https://atomicdata.dev/datatypes/float',
  INTEGER = 'https://atomicdata.dev/datatypes/integer',
  /** UTF-8 Markdown string */
  MARKDOWN = 'https://atomicdata.dev/datatypes/markdown',
  /** Array of Resources and */
  RESOURCEARRAY = 'https://atomicdata.dev/datatypes/resourceArray',
  /** String with only letters, numbers and dashes in between */
  SLUG = 'https://atomicdata.dev/datatypes/slug',
  STRING = 'https://atomicdata.dev/datatypes/string',
  /** Milliseconds since unix epoch */
  TIMESTAMP = 'https://atomicdata.dev/datatypes/timestamp',
  UNKNOWN = 'unknown-datatype',
}`

if so it have to connect dev site as root host ?  sorry for this question, just confuse this logic .

**Comment by joepio** [comment]
I don't think these are fetched typically - even though they are retrievable URLs. In many cases, these URLs are just used as names.

However, if you edit a resource, some Property definitions are loaded, so there is some dependency to AtomicData.dev there. When Atomic Data Browser starts, it sends a request to https://atomicdata.dev/properties/, because it makes the app feel faster if you want to edit resources that use these properties.

**Comment by iRobinZhang** [comment]
if network broken, some data brow page of the  atomic_server can not render properly ...

**Comment by joepio** [comment]
Most seems to work, but edit forms only show `error`. I could work around this a little by adjusting the views. 

<img width="1302" alt="Screenshot 2023-03-03 at 10 29 28" src="https://user-images.githubusercontent.com/2183313/222683920-ea135d82-9d21-4a80-9407-7427bd62aeeb.png">


Also, I could probably change the `atomicdata.dev/properties` call to something that's included on the server. I'll have to think a bit more about that.

In the mean time, could you provide some more information about your usecase and a screenshot of what's wrong @iRobinZhang ? Thanks !

**Comment by iRobinZhang** [comment]
I just run the data-browers project from console,  then start the rust server , then open chrome web browser , navigate to 'http://localhost:5173/', 

 I try to create a 'Article' but the Article edit page not render as normal,  of course it works online but network broken, I meaning if internet disconnected then the edit Article page not works as expected

**Comment by joepio** [comment]
I can do this, which adds property labels to errored properties:

<img width="860" alt="Screenshot 2023-03-03 at 11 06 29" src="https://user-images.githubusercontent.com/2183313/222692345-f04e3956-23f6-42ac-bf13-9a790241e2cd.png">

And store all core properties on a specific endpoint / include them in the browser build step. Also possible.

**Comment by iRobinZhang** [comment]
![image](https://user-images.githubusercontent.com/87108368/222697495-e86e2b1d-0668-412a-a99c-f90a5de31db4.png)
![image](https://user-images.githubusercontent.com/87108368/222698216-0da0b596-5139-44fd-8b64-72b0de595bb5.png)

it looks strange  or maybe I have not explain my question clearly ...

**Comment by joepio** [comment]
I understant, to fix this we have two options: Include the atomicdata.dev ontology in the front-end, or the back-end.

I think including it in the back-end is a lit less error-prone, as that is the system that contains the `default_store.json` file. But that misses a few key properties (see `populate_base_models`), so it is incomplete and should not be used as-is.

- We could generate a `store_generated.json` during `build.rs` that we put in the `assets` dir, which will be included in the server binary, which in turn can be requested by the front-end.
- We could add an endpoint for `/base-store` or something that just returns all `atomicdata.dev` classes and properties. Perhaps this can simply be a Collection.
- We could let the front-end use the local `/collections/properties` instead of the one at `atomicdata.dev`, and let that _also include external properties_. This seems by far the simplest!

**Comment by iRobinZhang** [comment]
that would be great 👍

**Comment by joepio** [comment]
Done!
